# Generated by Django 4.1.5 on 2023-01-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название услуги')),
                ('shorttitle', models.CharField(max_length=200, verbose_name='Стоимость услуги')),
                ('content', models.TextField(verbose_name='Об услуге')),
                ('issued', models.DateTimeField()),
            ],
        ),
    ]
