# Generated by Django 4.1.5 on 2023-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(verbose_name='Об услуге'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='shorttitle',
            field=models.CharField(max_length=200, verbose_name='Стоимость услуги'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название услуги'),
        ),
    ]
