# Generated by Django 4.1.5 on 2023-01-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_articles_content_alter_articles_shorttitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=200, verbose_name='Имя')),
                ('option', models.CharField(choices=[('с', 'Собака'), ('к', 'Кот'), ('г', 'Грызуны'), ('п', 'Птица')], max_length=1)),
                ('content', models.TextField(verbose_name='Комментарии и замечания')),
               
                
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='issued',
            field=models.DateTimeField(verbose_name=''),
        ),
    ]
