# Generated by Django 4.1.5 on 2023-01-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_visitors_alter_articles_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
