# Generated by Django 4.1.5 on 2023-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
