# Generated by Django 4.1.5 on 2023-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_rename_name_visitors_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='option',
            field=models.CharField(choices=[('с', 'Собака'), ('к', 'Кот'), ('г', 'Грызуны'), ('п', 'Птица')], max_length=1, verbose_name='Вид питомца'),
        ),
    ]
