# Generated by Django 4.1.5 on 2023-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии и замечания'),
        ),
    ]
