# Generated by Django 4.1.5 on 2023-01-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_alter_visitors_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='option',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], max_length=100, verbose_name='Вид питомца'),
        ),
    ]
