# Generated by Django 4.1.5 on 2023-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_visitors_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='content',
            field=models.TextField(default='Стрижка', verbose_name='Вид услуги'),
        ),
    ]
