# Generated by Django 4.1.5 on 2023-01-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_visitors_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='add',
            field=models.TextField(default='Стрижка', verbose_name='Комментарии/пожелания'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='content',
            field=models.CharField(default='Стрижка', max_length=100, verbose_name='Вид услуги'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='option',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], default='Собака', max_length=100, verbose_name='Вид питомца'),
        ),
    ]
