# Generated by Django 4.1.5 on 2023-01-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_visitors_add_alter_visitors_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='add',
        ),
        migrations.AddField(
            model_name='visitors',
            name='optionvar',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], default='Первичный осмотр', max_length=100, verbose_name='Вид услуги'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии/пожелания'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='option',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], max_length=100, verbose_name='Вид питомца'),
        ),
    ]
