# Generated by Django 4.1.5 on 2023-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_remove_visitors_add_visitors_optionvar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='optionvar',
            field=models.CharField(choices=[('Первичный осмотр', 'Первичный осмотр'), ('Терапия', 'Терапия'), ('Стоматология', 'Стоматология'), ('Хирургия', 'Хирургия'), ('Кастрация/стерилизация', 'Кастрация/стерилизация')], default='Первичный осмотр', max_length=100, verbose_name='Вид услуги'),
        ),
    ]
