# Generated by Django 4.1.5 on 2023-01-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_visitor01'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor01',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии/пожелания'),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='option',
            field=models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], default='Собака', max_length=100, verbose_name='Вид питомца'),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='optionvar',
            field=models.CharField(choices=[('Первичный осмотр', 'Первичный осмотр'), ('Терапия', 'Терапия'), ('Стоматология', 'Стоматология'), ('Хирургия', 'Хирургия'), ('Кастрация/стерилизация', 'Кастрация/стерилизация')], default='Терапия', max_length=100, verbose_name='Вид услуги'),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='surname',
            field=models.CharField(default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='visitor01',
            name='title',
            field=models.CharField(default='', max_length=250, verbose_name='Фамилия'),
        ),
    ]
