# Generated by Django 4.1.5 on 2023-01-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_visitor02'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Фамилия')),
                ('surname', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('option', models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], default='Собака', max_length=100, verbose_name='Вид питомца')),
                ('optionvar', models.CharField(choices=[('Первичный осмотр', 'Первичный осмотр'), ('Терапия', 'Терапия'), ('Стоматология', 'Стоматология'), ('Хирургия', 'Хирургия'), ('Кастрация/стерилизация', 'Кастрация/стерилизация')], default='Хирургия', max_length=100, verbose_name='Вид услуги')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Комментарии/пожелания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата записи')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Фамилия')),
                ('surname', models.CharField(default='', max_length=200, verbose_name='Имя')),
                ('option', models.CharField(choices=[('Собака', 'Собака'), ('Кот', 'Кот'), ('Грызун', 'Грызуны'), ('Птица', 'Птица')], default='Собака', max_length=100, verbose_name='Вид питомца')),
                ('optionvar', models.CharField(choices=[('Первичный осмотр', 'Первичный осмотр'), ('Терапия', 'Терапия'), ('Стоматология', 'Стоматология'), ('Хирургия', 'Хирургия'), ('Кастрация/стерилизация', 'Кастрация/стерилизация')], default='Кастрация/стерилизация', max_length=100, verbose_name='Вид услуги')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Комментарии/пожелания')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата записи')),
            ],
        ),
    ]
