# Generated by Django 4.1.5 on 2023-02-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_visitor03_visitor04'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor01',
            name='optionvartwo',
            field=models.CharField(choices=[('Первичный осмотр', 'Первичный осмотр'), ('Терапия', 'Терапия'), ('Стоматология', 'Стоматология'), ('Хирургия', 'Хирургия'), ('Кастрация/стерилизация', 'Кастрация/стерилизация')], default='Стоматология', max_length=100, verbose_name='Вид услуги'),
        ),
    ]
