# Generated by Django 4.1.5 on 2023-02-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_delete_visitor01_delete_visitor02_delete_visitor03_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True, verbose_name='Дата записи'),
        ),
    ]
