# Generated by Django 4.1.5 on 2023-02-02 14:40

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_alter_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(max_length=5, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:/\\d+)*\\Z'), code='invalid', message='Превышено колличество символов')], verbose_name='Дата записи'),
        ),
    ]
