# Generated by Django 4.1.5 on 2023-02-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_alter_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(max_length=16, null=True, unique=True, verbose_name='Дата записи'),
        ),
    ]
