# Generated by Django 4.1.5 on 2023-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_alter_visitors_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=200, verbose_name='Имя')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Ваш отзыв')),
                ('choice', models.CharField(choices=[('Отличное', 'Отличное'), ('Удволетворительное', 'Удволетворительное'), ('Неудволетворительное', 'Неудволетворительное')], default='Отличное', max_length=100, verbose_name='Моя оценка')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(max_length=14, null=True, unique=True, verbose_name='Дата записи'),
        ),
    ]
