# Generated by Django 4.1.5 on 2023-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0033_doctors_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='month',
            field=models.CharField(choices=[('Января', 'Января'), ('Февраля', 'Февраля'), ('Марта', 'Марта'), ('Апреля', 'Апреля'), ('Мая', 'Мая'), ('Июня', 'Июня'), ('Июля', 'Июля'), ('Августа', 'Августа'), ('Сентября', 'Сентября'), ('Октября', 'Октября'), ('Ноября', 'Ноября'), ('Декабря', 'Декабря')], default='1', max_length=100, verbose_name='Месяц записи'),
        ),
        migrations.AddField(
            model_name='visitors',
            name='time',
            field=models.CharField(max_length=5, null=True, unique=True, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '31')], default='1', max_length=100, verbose_name='Дата записи'),
        ),
    ]
