# Generated by Django 4.1.5 on 2023-02-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_alter_visitors_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='title',
            new_name='titl',
        ),
    ]
