# Generated by Django 4.1.5 on 2023-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0037_rename_title_articles_titl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(max_length=2, null=True, unique=True, verbose_name='Дата записи'),
        ),
    ]
