# Generated by Django 4.1.5 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0039_alter_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='time',
            field=models.CharField(default='00:00', max_length=5, null=True, verbose_name='Время записи'),
        ),
    ]
