# Generated by Django 4.1.5 on 2023-02-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_alter_visitors_date_alter_visitors_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.IntegerField(default='31', verbose_name='Дата записи'),
        ),
    ]
