# Generated by Django 4.1.5 on 2023-02-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_alter_visitors_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='time',
            field=models.CharField(default='09:00', max_length=5, null=True, unique=True, verbose_name='Время записи'),
        ),
    ]
