# Generated by Django 4.1.5 on 2023-02-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0044_alter_visitors_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='month',
        ),
        migrations.AlterField(
            model_name='visitors',
            name='time',
            field=models.CharField(default='01/01 10:00', max_length=11, null=True, unique=True, verbose_name='Время записи'),
        ),
    ]
