# Generated by Django 4.1.5 on 2023-01-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[('c', 'copyright'), ('m', 'merket')], max_length=1),
        ),
    ]
